function getUniqueId() {
  const timestamp = Date.now(); // ~13 digits
  const array = new Uint32Array(1);
  crypto.getRandomValues(array);
  const random = array[0].toString().padStart(10, "0"); // 10 random digits
  return Number(`${timestamp}${random.slice(0, 5)}`); // keep it within safe range
}

enum CourseType {
  Lecture = "Lecture",
  Lab = "Lab",
  Online = "Online",
  Other = "Other",
}

enum Semester {
  Fall = "Fall",
  Spring = "Spring",
  Summer = "Summer",
  Winter = "Winter",
}

enum Day {
  Monday = "Monday",
  Tuesday = "Tuesday",
  Wednesday = "Wednesday",
  Thursday = "Thursday",
  Friday = "Friday",
  Saturday = "Saturday",
  Sunday = "Sunday",
}

type ClassTime = {
  start: Date;
  end: Date;
};

type ScheduleType = {
  Day: Set<ClassTime>;
};

interface VTCourseStructure {
  get id(): number;
  get name(): string;
  get schedule(): ScheduleType;
}

interface VTClassStructure {
  get courses(): VTCourseStructure[];
  get id(): string;
}

enum VTSubject {
  AAD = "AAD",
  AAEC = "AAEC",
  ACIS = "ACIS",
  ADS = "ADS",
  ADV = "ADV",
  AFST = "AFST",
  AHRM = "AHRM",
  AINS = "AINS",
  AIS = "AIS",
  ALCE = "ALCE",
  ALS = "ALS",
  AOE = "AOE",
  APS = "APS",
  APSC = "APSC",
  ARBC = "ARBC",
  ARCH = "ARCH",
  ART = "ART",
  AS = "AS",
  ASPT = "ASPT",
  AT = "AT",
  BC = "BC",
  BCHM = "BCHM",
  BDS = "BDS",
  BIOL = "BIOL",
  BIT = "BIT",
  BMES = "BMES",
  BMSP = "BMSP",
  BMVS = "BMVS",
  BSE = "BSE",
  CEE = "CEE",
  CEM = "CEM",
  CHE = "CHE",
  CHEM = "CHEM",
  CHN = "CHN",
  CINE = "CINE",
  CLA = "CLA",
  CMDA = "CMDA",
  CMST = "CMST",
  CNST = "CNST",
  COMM = "COMM",
  CONS = "CONS",
  COS = "COS",
  CRIM = "CRIM",
  CS = "CS",
  CSES = "CSES",
  DANC = "DANC",
  DASC = "DASC",
  ECE = "ECE",
  ECON = "ECON",
  EDCI = "EDCI",
  EDCO = "EDCO",
  EDCT = "EDCT",
  EDEL = "EDEL",
  EDEP = "EDEP",
  EDHE = "EDHE",
  EDIT = "EDIT",
  EDP = "EDP",
  EDRE = "EDRE",
  EDTE = "EDTE",
  ENGE = "ENGE",
  ENGL = "ENGL",
  ENGR = "ENGR",
  ENSC = "ENSC",
  ENT = "ENT",
  ESM = "ESM",
  FIN = "FIN",
  FIW = "FIW",
  FL = "FL",
  FMD = "FMD",
  FR = "FR",
  FREC = "FREC",
  FST = "FST",
  GBCB = "GBCB",
  GEOG = "GEOG",
  GEOS = "GEOS",
  GER = "GER",
  GIA = "GIA",
  GR = "GR",
  GRAD = "GRAD",
  HD = "HD",
  HEB = "HEB",
  HIST = "HIST",
  HNFE = "HNFE",
  HORT = "HORT",
  HTM = "HTM",
  HUM = "HUM",
  IDS = "IDS",
  IS = "IS",
  ISC = "ISC",
  ISE = "ISE",
  ITAL = "ITAL",
  ITDS = "ITDS",
  JMC = "JMC",
  JPN = "JPN",
  JUD = "JUD",
  LAHS = "LAHS",
  LAR = "LAR",
  LAT = "LAT",
  LDRS = "LDRS",
  MACR = "MACR",
  MATH = "MATH",
  ME = "ME",
  MED = "MED",
  MGT = "MGT",
  MINE = "MINE",
  MKTG = "MKTG",
  MN = "MN",
  MS = "MS",
  MSE = "MSE",
  MTRG = "MTRG",
  MUS = "MUS",
  NANO = "NANO",
  NEUR = "NEUR",
  NR = "NR",
  NSEG = "NSEG",
  PAPA = "PAPA",
  PHIL = "PHIL",
  PHS = "PHS",
  PHYS = "PHYS",
  PM = "PM",
  PORT = "PORT",
  PPE = "PPE",
  PPWS = "PPWS",
  PR = "PR",
  PSCI = "PSCI",
  PSVP = "PSVP",
  PSYC = "PSYC",
  REAL = "REAL",
  RED = "RED",
  RLCL = "RLCL",
  RTM = "RTM",
  RUS = "RUS",
  SBIO = "SBIO",
  SOC = "SOC",
  SPAN = "SPAN",
  SPES = "SPES",
  SPIA = "SPIA",
  STAT = "STAT",
  STL = "STL",
  STS = "STS",
  SYSB = "SYSB",
  TA = "TA",
  TBMH = "TBMH",
  UAP = "UAP",
  UH = "UH",
  UNIV = "UNIV",
  VM = "VM",
  WATR = "WATR",
  WGS = "WGS",
}
